llm: llama2 #alternative: GPT4, GPT4-o
number_of_chunks: 10
llama2: /Users/Kenneth/PycharmProjects/knowledgeGraph/data/models/llama-2-7b-chat.Q5_K_M.gguf
llama3: /Users/Kenneth/PycharmProjects/knowledgeGraph/data/models/Meta-Llama-3-8B.Q5_K_M.gguf
modelling_location: cluster
